Feat: cognito login react implementation

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -69,14 +69,14 @@ jobs:
         run: |
           amplify_app_id=$(aws amplify list-apps --query "apps[?name=='${{ env.AMPLIFY_APP_NAME }}'].appId" --output text)
           echo "AMPLIFY_APP_ID=$amplify_app_id" >> $GITHUB_ENV
-      - name: Retrieve Amplify Branch URL
+      - name: Retrieve Amplify app URL
         run: |
-            if [ -z "${{ env.AMPLIFY_APP_ID }}" ]; then
-              echo "Amplify App ID is missing"
-              exit 1
-            fi
-            amplify_branch_url=$(aws amplify get-branch --app-id ${{ env.AMPLIFY_APP_ID }} --branch-name feature/frontend_gh_deploy --query 'branch.branchUrl' --output text)
-            echo "AMPLIFY_BRANCH_URL=$amplify_branch_url" >> $GITHUB_ENV
+          if [ -z "${AMPLIFY_APP_ID}" ]; then
+            echo "Amplify App ID is missing"
+            exit 1
+          fi
+          amplify_app_url=$(aws amplify get-app --app-id $AMPLIFY_APP_ID --query 'app.defaultDomain' --output text)
+          echo "AMPLIFY_APP_URL=$amplify_app_url" >> $GITHUB_ENV
       - name: Deploy CloudFormation stack for cognito
         run: |
                 aws cloudformation deploy \
